import { StoreType } from "../types";

/* new Array(10000).fill({
    id: 1,
    name: "Campera1",
    brand: "Nike",
    categories: ["campera"],
    color: "black",
    currentStock: 34,
    price: 10000,
    discountPercentage: 0.5,
    description: "Campera 1",
    url_img: "../campera01.jpg",
    sizes: ["Hombre"],
    minimum: 0,
    reorderPoint:100,
}) */

/* const randomStringArr = [...Array(50)].map(() => {
    const randomStr = "abcdefghijklmnopqrstuvwxyz"
        .split("")
        .sort(() => 0.5 - Math.random())
        .join("");
    return randomStr.slice(0, Math.random() * 26 + 2);
}); */

export const store1: StoreType = {
    name: "Tienda 1",
    colors: {
        primary: { hue: 233, sat: 29, light: 12 },
        secondary: { hue: 187, sat: 56, light: 38 },
    },
    products: [
        {
            id: 1,
            name: "Campera1",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.5,
            description: "Campera 1",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 2,
            name: "Campera2",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 2",
            url_img: "../campera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 3,
            name: "Campera3",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 3",
            url_img: "../campera01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 4,
            name: "Campera4",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 4",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 5,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.4,
            description: "Zapatillas 1",
            url_img: "../zapatillas01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 6,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 2",
            url_img: "../zapatillas01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 7,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 8,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 9,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 10,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 11,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 12,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 13,
            name: "Campera1",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.5,
            description: "Campera 1",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 14,
            name: "Campera2",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 2",
            url_img: "../campera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 15,
            name: "Campera3",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 3",
            url_img: "../campera01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 16,
            name: "Campera4",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 4",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 17,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.4,
            description: "Zapatillas 1",
            url_img: "../zapatillas01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 18,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 2",
            url_img: "../zapatillas01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 19,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 20,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 21,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 22,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 23,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 24,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
    ],
};
export const store2: StoreType = {
    name: "Tienda 2",
    colors: {
        primary: { hue: 331, sat: 96, light: 43 },
        secondary: { hue: 51, sat: 100, light: 50 },
    },
    products: [
        {
            id: 1,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 2,
            name: "Pantalon2",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon2",
            url_img: "../pantalon01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 3,
            name: "Pantalon3",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.7,
            description: "Pantalon3",
            url_img: "../pantalon01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 4,
            name: "Pantalon4",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon4",
            url_img: "../pantalon01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 5,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 6,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 7,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 8,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 2",
            url_img: "../zapatillas02.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 9,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 10,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.6,
            description: "Zapatillas 2",
            url_img: "../zapatillas03.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 11,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 12,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 13,
            name: "Campera1",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.5,
            description: "Campera 1",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 14,
            name: "Campera2",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 2",
            url_img: "../campera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 15,
            name: "Campera3",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 3",
            url_img: "../campera01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 16,
            name: "Campera4",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 4",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 17,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.4,
            description: "Zapatillas 1",
            url_img: "../zapatillas01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 18,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 2",
            url_img: "../zapatillas01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 19,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 20,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 21,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 22,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 23,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 24,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
    ],
};
export const store3: StoreType = {
    name: "Tienda 3",
    colors: {
        primary: { hue: 11, sat: 96, light: 40 },
        secondary: { hue: 32, sat: 100, light: 73 },
    },
    products: [
        {
            id: 1,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 2,
            name: "Remera2",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera2",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 3,
            name: "Remera3",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera3",
            url_img: "../remera01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 4,
            name: "Remera4",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera4",
            url_img: "../remera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 5,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas02.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 6,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.6,
            description: "Zapatillas 2",
            url_img: "../zapatillas03.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 7,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas03.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 8,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 9,
            name: "Pantalon4",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon4",
            url_img: "../pantalon01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 10,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.6,
            description: "Zapatillas 2",
            url_img: "../zapatillas03.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 11,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 12,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 13,
            name: "Campera1",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.5,
            description: "Campera 1",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 14,
            name: "Campera2",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 2",
            url_img: "../campera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 15,
            name: "Campera3",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 3",
            url_img: "../campera01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 16,
            name: "Campera4",
            brand: "Nike",
            categories: ["campera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Campera 4",
            url_img: "../campera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 17,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 0.4,
            description: "Zapatillas 1",
            url_img: "../zapatillas01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 18,
            name: "Zapatillas2",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 2",
            url_img: "../zapatillas01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 19,
            name: "Zapatillas3",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 3",
            url_img: "../zapatillas01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 20,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 21,
            name: "Pantalon1",
            brand: "Nike",
            categories: ["pantalon"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Pantalon 1",
            url_img: "../pantalon01.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 22,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Hombre"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 23,
            name: "Remera1",
            brand: "Nike",
            categories: ["remera"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Remera1",
            url_img: "../remera01.jpg",
            sizes: ["Mujer"],
            minimum: 0,
            reorderPoint: 100,
        },
        {
            id: 24,
            name: "Zapatillas1",
            brand: "Nike",
            categories: ["zapatilla"],
            color: "black",
            currentStock: 34,
            price: 10000,
            discountPercentage: 1,
            description: "Zapatillas 1",
            url_img: "../zapatillas02.jpg",
            sizes: ["Niños"],
            minimum: 0,
            reorderPoint: 100,
        },
    ],
};
