export const store1 = [
    {
        id: 1,
        name: "Campera1",
        category: ["campera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 0.5,
        description: "Campera 1",
        url_img: "../campera01.jpg",
    },
    {
        id: 2,
        name: "Campera2",
        category: ["campera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Campera 2",
        url_img: "../campera01.jpg",
    },
    {
        id: 3,
        name: "Campera3",
        category: ["campera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Campera 3",
        url_img: "../campera01.jpg",
    },
    {
        id: 4,
        name: "Campera4",
        category: ["campera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Campera 4",
        url_img: "../campera01.jpg",
    },
    {
        id: 5,
        name: "Zapatillas1",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 0.4,
        description: "Zapatillas 1",
        url_img: "../zapatillas01.jpg",
    },
    {
        id: 6,
        name: "Zapatillas2",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 2",
        url_img: "../zapatillas01.jpg",
    },
    {
        id: 7,
        name: "Zapatillas3",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 3",
        url_img: "../zapatillas01.jpg",
    },
    {
        id: 8,
        name: "Pantalon1",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Pantalon 1",
        url_img: "../pantalon01.jpg",
    },
    {
        id: 9,
        name: "Pantalon1",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Pantalon 1",
        url_img: "../pantalon01.jpg",
    },
    {
        id: 10,
        name: "Remera1",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera1",
        url_img: "../remera01.jpg",
    },
    {
        id: 11,
        name: "Remera1",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera1",
        url_img: "../remera01.jpg",
    },
    {
        id: 12,
        name: "Zapatillas1",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 1",
        url_img: "../zapatillas02.jpg",
    },
];

export const store2 = [
    {
        id: 1,
        name: "Pantalon1",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Pantalon 1",
        url_img: "../pantalon01.jpg",
    },
    {
        id: 2,
        name: "Pantalon2",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Pantalon2",
        url_img: "../pantalon01.jpg",
    },
    {
        id: 3,
        name: "Pantalon3",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 0.7,
        description: "Pantalon3",
        url_img: "../pantalon01.jpg",
    },
    {
        id: 4,
        name: "Pantalon4",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Pantalon4",
        url_img: "../pantalon01.jpg",
    },
    {
        id: 5,
        name: "Remera1",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera1",
        url_img: "../remera01.jpg",
    },
    {
        id: 6,
        name: "Remera1",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera1",
        url_img: "../remera01.jpg",
    },
    {
        id: 7,
        name: "Zapatillas1",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 1",
        url_img: "../zapatillas02.jpg",
    },
    {
        id: 8,
        name: "Zapatillas2",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 2",
        url_img: "../zapatillas02.jpg",
    },
    {
        id: 9,
        name: "Zapatillas3",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 3",
        url_img: "../zapatillas02.jpg",
    },
    {
        id: 10,
        name: "Zapatillas2",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 0.6,
        description: "Zapatillas 2",
        url_img: "../zapatillas03.jpg",
    },
];

export const store3 = [
    {
        id: 1,
        name: "Remera1",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera1",
        url_img: "../remera01.jpg",
    },
    {
        id: 2,
        name: "Remera2",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera2",
        url_img: "../remera01.jpg",
    },
    {
        id: 3,
        name: "Remera3",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera3",
        url_img: "../remera01.jpg",
    },
    {
        id: 4,
        name: "Remera4",
        category: ["remera"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Remera4",
        url_img: "../remera01.jpg",
    },
    {
        id: 5,
        name: "Zapatillas3",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 3",
        url_img: "../zapatillas02.jpg",
    },
    {
        id: 6,
        name: "Zapatillas2",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 0.6,
        description: "Zapatillas 2",
        url_img: "../zapatillas03.jpg",
    },
    {
        id: 7,
        name: "Zapatillas3",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 3",
        url_img: "../zapatillas03.jpg",
    },
    {
        id: 8,
        name: "Zapatillas3",
        category: ["zapatilla"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Zapatillas 3",
        url_img: "../zapatillas01.jpg",
    },
    {
        id: 9,
        name: "Pantalon4",
        category: ["pantalon"],
        color: "black",
        stock: 34,
        price: 10000,
        discount: 1,
        description: "Pantalon4",
        url_img: "../pantalon01.jpg",
    },
];
